### ISSUE TITLE
Invalid Colour Error

### ISSUE THREAD

**Issue by RimishRobolab** [carlosperate/ardublockly#100]
![image](https://cloud.githubusercontent.com/assets/19488511/16449697/9404dfaa-3e16-11e6-860e-9d1b6e302064.png)
![image](https://cloud.githubusercontent.com/assets/19488511/16449720/aa9dec5c-3e16-11e6-968d-648161aa1ed7.png)

**Comment by carlosperate** [comment]
It's really hard to debug without having your code changes to Ardublockly. Based on the screenshots it sounds like you've added new blocks to the toolbox with an incorrect colour value, or that you've modified any of the motor blocks `setColour` input argument.

**Comment by RimishRobolab** [comment]
Hi Sir,
Thanks for help
Problem is solved. There was a problem with servo.js file. I think by mistake I would have edited the setColour argument.

**Comment by carlosperate** [comment]
Glad it is working now :)
