### ISSUE TITLE
Ardublockly Building

### ISSUE THREAD

**Issue by RimishRobolab** [carlosperate/ardublockly#102]
I want to create ardublockly exe file. I tried documentation from below link https://github.com/carlosperate/ardublockly/wiki/Building-Ardublockly.
I have installed everything and then did 1st step python server (platform dependent)
It has created batch file in root directory and arduexec folder.
but inside arduexec folder, there is only a server folder. there is not any ardublockly.exe present.

**Comment by carlosperate** [comment]
You need to continue with the instructions to get the exe file created on the right location, you will need node with npm for that.

**Comment by RimishRobolab** [comment]
I already Installed python, pip, py2exe, Mkdocs, node.js
step 1) for windows build
python package\build_py2exe.py
It give me following error
![image](https://cloud.githubusercontent.com/assets/19488511/16561715/54af470e-4218-11e6-8ba3-36b771da8733.png)

![image](https://cloud.githubusercontent.com/assets/19488511/16561674/0b85f6e0-4218-11e6-9ccf-58605f0a01e0.png)
