### ISSUE TITLE
serial monitor in ardublockly

### ISSUE THREAD

**Issue by RimishRobolab** [carlosperate/ardublockly#106]
how to open serial monitor of arduino IDE in ardublockly

**Comment by carlosperate** [comment]
You are going to be a little bit more specific. You can select the Arduino COM port in the settings for loading the program, but if you want to get the serial data you will have to use the Arduino IDE directly.

**Comment by carlosperate** [comment]
I hope your question was answered, if it hasn't please feel free to reopen this issue.

**Comment by Lapjeskater** [comment]
Hey Carlosperate,
I'm using the windows (desktop) version of ardublockly to teach a group of children the basics of programming and robotics.
It would love to have a direct option to start a serial monitor from the ardublockly window, so the users don't have to do anything with the arduino program at all.

**Comment by carlosperate** [comment]
Hi @Lapjeskater, I assume you mean something as described in https://github.com/carlosperate/ardublockly/issues/29 rather opening the Arduino IDE Serial monitor directly?

**Comment by Lapjeskater** [comment]
Ah I didn't see that one, this issue popped up higher in the search. Any time schedule about when its going to be implemented? 
Love the program so far!
