### ISSUE TITLE
ardublockly error

### ISSUE THREAD

**Issue by RimishRobolab** [carlosperate/ardublockly#109]
I have embedded blockly turtle game in ardublockly. 
I have created two tabs one for ardublockly and one for blockly turtle game
![image](https://cloud.githubusercontent.com/assets/19488511/17212345/47ad594c-54ec-11e6-9f48-6af1884c0e72.png)
![image](https://cloud.githubusercontent.com/assets/19488511/17212356/58211944-54ec-11e6-8824-3e3845ac532d.png)
It is running properly in blockly web version
I have created one ardublockly exe file
In ardublockly exe version it is not showing when i click blockly game tab
![image](https://cloud.githubusercontent.com/assets/19488511/17212407/ad20138c-54ec-11e6-85c4-ec2807e9fc4a.png)
check code link below
https://drive.google.com/file/d/0B9YgAk1hTD6gUXB5d2Nvd3VCX00/view?usp=sharing

**Comment by RimishRobolab** [comment]
I did not get the answer from anyone for this error

**Comment by RimishRobolab** [comment]
Hello Carlos Sir,
Can you help me to solve this error

**Comment by carlosperate** [comment]
Hi Rimish,
Do you still need help with this?

**Comment by RimishRobolab** [comment]
Yes Sir.

**Comment by RimishRobolab** [comment]
Hey Carlos, have you checked out this above error

**Comment by RimishRobolab** [comment]
Hey Carlos, You have not given me any reply yet. Have you checked it?

**Comment by carlosperate** [comment]
Finally had a chance to have a look.
You need to move the new javascript using jquery at the top of the html document to the end of the page, after the init function. This is because jquery is not loaded the same way under electron (that's why there is a ardublocly_desktop.js script).
