### ISSUE TITLE
Ardublockly Extract and Delete Error

### ISSUE THREAD

**Issue by RimishRobolab** [carlosperate/ardublockly#111]
I have downloaded ardublockly folder and package folder from github but when I try to copy it in some other devices or drive it gives me error
I have downloaded the complete package of ardublockly. There is one package folder inside ardublockly It is giving me error while copying or deleting complete ardublockly folder then I tried making its zip file it went successful but when i extracted that zip file again it was giving me error that your file path is too long.
![screenshot_2](https://cloud.githubusercontent.com/assets/19488511/17587380/a45b92f4-5fe5-11e6-9d1a-b6f3ddd6ea4c.png)
It will not be helpful to download the ardublockly everytime from github because i have done some changes in ardublockly and want to use it in other devices.
[winrar error.txt](https://github.com/carlosperate/ardublockly/files/413068/winrar.error.txt)
![winrar error](https://cloud.githubusercontent.com/assets/19488511/17587480/54e89b44-5fe6-11e6-8462-3eb2fdcb0553.png)

**Comment by carlosperate** [comment]
You are using an old version of npm. This is a known issue with the way npm nested dependencies which has been resolved not that long ago. If you google a little bit there is a lot of info explaining the problem and possible solutions: http://stackoverflow.com/questions/35632789/windows-error-deleting-node-modules-folder-source-path-too-long
