### ISSUE TITLE
Open and Save option

### ISSUE THREAD

**Issue by RimishRobolab** [carlosperate/ardublockly#112]
I have created two tabs in ardublockly one for ardublockly and other one is for blockly games
there is open and save option in ardublockly but it is for ardublockly blocks. I have added blockly games and I want the same feature open and save blocks for blockly games.
![image](https://cloud.githubusercontent.com/assets/19488511/17587809/20151c06-5fe8-11e6-8908-84810c1e3cf6.png)
![image](https://cloud.githubusercontent.com/assets/19488511/17587936/094dd2dc-5fe9-11e6-8968-c37672e25d3f.png)

**Comment by carlosperate** [comment]
This is more of a general implementation query than an issue and I am not quite sure what you are asking exactly. If you have created two different Blockly  workspaces you can create two different open and save functions targeting each workspace.
