### ISSUE TITLE
Variable names with a space generates inconsistent c code

### ISSUE THREAD

**Issue by ELundby45** [carlosperate/ardublockly#119]
When a variable name has a space in it, it is correctly changed to an underscore when being set, but the global definition still contains a space. 

![image](https://cloud.githubusercontent.com/assets/373868/18481037/02032338-7998-11e6-9b3d-335412406dd6.png)

**Comment by carlosperate** [comment]
Fixed on PR https://github.com/carlosperate/ardublockly/pull/120. Thanks @ELundby45 !
