### ISSUE TITLE
windows v.0.1.2 error when trying to run ardublockly_run.bat

### ISSUE THREAD

**Issue by Simsmzzms** [carlosperate/ardublockly#128]
Downloaded most recent v. of ardublockly, but when trying to run the "pre-packaged" executable I repeatedly encounter an error. 

Restarting and all basic fixes have been tried. After I close the error message, the program runs but all of the GUI is does not appear.

The core version will open in Chrome but the GUI is totally unresponsive. Have I forgotten to do something?....I thought this file after extraction was meant to be self-enclosed.

Any suggestions would be greatly appreciated, thanks!

**Comment by Simsmzzms** [comment]
It shows up as a JavaScript error. I tried re-extracting, and extracting the folder within the arduexec folder. As well as replacing the arduexec/server folder from the last build. Still no dice.

**Comment by Simsmzzms** [comment]
Even the last build v.1.1 isnt running. Please help.

**Comment by carlosperate** [comment]
If you can copy the error here I can then try to investigate?
I would also need the contents of the ardublockly.log file, so if you could upload it somewhere or copy it here it would be quite useful.

**Comment by Simsmzzms** [comment]
Hi carlos,

Below is the info you asked for. Hopefully this clarifies the issues some.

Thank you so so much!

[ardublockly.txt](https://github.com/carlosperate/ardublockly/files/566617/ardublockly.txt)
![capture](https://cloud.githubusercontent.com/assets/23213062/19930129/e75aacde-a0fe-11e6-8772-896bf8c1c646.PNG)
![n](https://cloud.githubusercontent.com/assets/23213062/19930131/e9160fdc-a0fe-11e6-8b46-05209cbb5047.PNG)

**Comment by carlosperate** [comment]
Could you confirm that the arduexec\server\start.exe file exists and that
you can execute it successfully? It should open a command line window with
some information and automatically open your default browser pointing to
the Ardublockly web interface. If it does open correctly, could you copy
and paste the contents of the console here as well?

Thanks,
Carlos

**Comment by Simsmzzms** [comment]
@ C:\ardublockly\arduexec\server                  no start.exe file exists

Within that there is a folder called library which i've extracted. Is the start.exe file located in here? 

Otherwise what are your suggestions? Thanks again.

**Comment by Simsmzzms** [comment]
![start](https://cloud.githubusercontent.com/assets/23213062/19933554/ac5e6370-a10b-11e6-83de-d31f12b4406e.PNG)

**Comment by Simsmzzms** [comment]
what scripts should be contained? I can try and make my own

**Comment by carlosperate** [comment]
These are the contents from the zip file downloaded from the github releases link:

![zipfile](https://cloud.githubusercontent.com/assets/4189262/19934052/5ac56bba-a10d-11e6-802c-d4fa9cc97af6.png)

There should not be any need to rebuild the python server. Could you try to download the zip file and try again?

**Comment by Simsmzzms** [comment]
Hi Carlos, sorry for the delay, I've done what you said and have managed to locate/execute the start.exe within the arduexec\server folder. Below are the contents of the console. Once again thank you so much, I'm excited to start utilizing this implementation.

![console](https://cloud.githubusercontent.com/assets/23213062/19961451/9fafdd62-a1aa-11e6-8db9-1851bebb4ceb.PNG)

**Comment by Simsmzzms** [comment]
No need to further assist, everything is working wonderfully at this point. Its great!

**Comment by carlosperate** [comment]
Glad you git it working @Simsmzzms!
