### ISSUE TITLE
How to Add Russian Language

### ISSUE THREAD

**Issue by mrobotby** [carlosperate/ardublockly#136]
Hi. I want to add Russian language, but it seems not working well( Because when I try to add Russian language, only ??????? characters appear instead of normal letters. Are you able to help me with this issue?
Thank you.

**Comment by carlosperate** [comment]
Could you post a screenshot or a link to a repository with the issue? It would help me figure out what the problem could be.

**Comment by mrobotby** [comment]
I just can't understand how to add new language. How to add new? Because in guide is not clear description.

**Comment by mrobotby** [comment]
First I open blockly/msg directory. There is only one file messages.js
But in this directory no file blockly/msg/<language>.js How to create it?
Also I don't know how add Russian block to choose in menu of the application (front end).

**Comment by mrobotby** [comment]
<img width="960" alt="2017-01-10 23 48 13" src="https://cloud.githubusercontent.com/assets/14249390/21824173/3962202c-d78f-11e6-94a8-c7e2769230f0.png">
It looks like this. 1. I just added file ru.js to directory ardublockly\ardublockly\msg 

2. And added a line for front-end to choose Russian language in Settings menu here ardublockly_lang.js in directory ardublockly\ardublockly
3. Then I just run start.py (without any build of the program).
Where is the problem? Help me please.
ru.js file and ardublockly_lang.js are below

// ru.js
var Ardublockly = Ardublockly || {};
Ardublockly.LOCALISED_TEXT = {
  translationLanguage: "Русский",
  title: "MBlockly",
  blocks: "Blocks",
  /* Menu */
  open: "Открыть",
  save: "Сохранить",
  deleteAll: "Удалить все",
  settings: "Настройки",
  documentation: "Документация",
  reportBug: "Сообщить об ошибке",
  examples: "Примеры",
  /* Settings */
  compilerLocation: "Путь к компилятору",
  compilerLocationDefault: "Путь к компилятору неизвестен",
  sketchFolder: "Папка со скетчами",
  sketchFolderDefault: "Папка со скетчами неизвестна",
  arduinoBoard: "Ардуино плата",
  arduinoBoardDefault: "Ардуино плата неизвестная",
  comPort: "COM Порт",
  comPortDefault: "COM Порт неизвестен",
  defaultIdeButton: "Default IDE Button",
  defaultIdeButtonDefault: "IDE опции неизвестны",
  language: "Язык",
  languageDefault: "Язык неизвестен",
  sketchName: "Имя скетча",
  /* Arduino console output */
  arduinoOpMainTitle: "Arduino IDE вывод",
  arduinoOpWaiting: "Ждем IDE вывод...",
  arduinoOpUploadedTitle: "Скетч успешно загружен",
  arduinoOpVerifiedTitle: "Скетч успешно скомпилирован",
  arduinoOpOpenedTitle: "Скетч был открыт в Arduino IDE",
  arduinoOpOpenedBody: "Скетч должен быть загружен в Arduino IDE.",
  arduinoOpErrorUpVerTitle: "Компиляция или загрузка провалились",
  arduinoOpErrorSketchTitle: "Скетч не найден",
  arduinoOpErrorFlagTitle: "Неправильный command line аргумент",
  arduinoOpErrorFlagPrefTitle: "Preference passed to 'get-pref' flag does not exist",
  arduinoOpErrorIdeDirTitle: "Unable to find Arduino IDE",
  arduinoOpErrorIdeDirBody: "The compiler directory has not been set.<br>" +
                            "Please set it in the Settings.",
  arduinoOpErrorIdeOptionTitle: "What should we do with the Sketch?",
  arduinoOpErrorIdeOptionBody: "The launch IDE option has not been set.<br>" +
                               "Please select an IDE option in the Settings.",
  arduinoOpErrorIdePortTitle: "Serial Port unavailable",
  arduinoOpErrorIdePortBody: "The Serial Port is not accessible.<br>" +
                             "Please check if the Arduino is correctly connected to the PC and select the Serial Port in the Settings.",
  arduinoOpErrorIdeBoardTitle: "Unknown Arduino Board",
  arduinoOpErrorIdeBoardBody: "The Arduino Board has not been set.<br>" +
                              "Please select the appropriate Arduino Board from the settings.",
  /* Modals */
  noServerTitle: "Ardublockly app not running",
  noServerTitleBody: "<p>For all the Ardublockly features to be enabled, the Ardublockly desktop application must be running locally on your computer.</p>" +
                     "<p>If you are using an online version you will not be able to configure the settings nor load the blocks code into an Arduino.</p>" +
                     "<p>Installation instruction can be found in the <a href=\"https://github.com/carlosperate/ardublockly\">Ardublockly repository</a>.</p>" +
                     "<p>If you have Ardublockly already installed, make sure the application is running correctly.</p>",
  noServerNoLangBody: "If the Ardublockly application is not running the language cannot be fully changed.",
  addBlocksTitle: "Additional Blocks",
  /* Alerts */
  loadNewBlocksTitle: "Load new blocks?",
  loadNewBlocksBody: "Loading a new XML file will replace the current blocks from the workspace.<br>" +
                     "Are you sure you want to proceed?",
  discardBlocksTitle: "Delete blocks?",
  discardBlocksBody: "There are %1 blocks on the workspace.<br>" +
                     "Are you sure you want to delete them?",
  invalidXmlTitle: "Invalid XML",
  invalidXmlBody: "The XML file was not successfully parsed into blocks. Please review the XML code and try again.",
  /* Tooltips */
  uploadingSketch: "Uploading Sketch into Arduino...",
  uploadSketch: "Upload Sketch to the Arduino",
  verifyingSketch: "Verifying Sketch...",
  verifySketch: "Verify the Sketch",
  openingSketch: "Opening Sketch in the Arduino IDE...",
  openSketch: "Open Sketch in IDE",
  notImplemented: "Function not yet implemented",
  /* Prompts */
  ok: "Ok",
  okay: "Okay",
  cancel: "Отменить",
  return: "Вернуться",
  /* Cards */
  arduinoSourceCode: "Arduino Source Code",
  blocksXml: "Blocks XML",
  /* Toolbox Categories*/
  catLogic: "Логика",
  catLoops: "Циклы",
  catMath: "Математика",
  catText: "Текст",
  catVariables: "Переменные",
  catFunctions: "Функции",
  catInputOutput: "Ввод/вывод",
  catTime: "Время",
  catAudio: "Аудио",
  catMotors: "Моторы",
  catComms: "Порты связи Comms",
};

//ardublockly_lang.js
/**
 * @license Licensed under the Apache License, Version 2.0 (the "License"):
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 * @fileoverview Functions related to language and localisation.
 */
'use strict';

/** Create a namespace for the application. */
var Ardublockly = Ardublockly || {};

/** Lookup for names of supported languages. Keys in ISO 639 format. */
Ardublockly.LANGUAGE_NAME = {
  'fr': 'Français',
  'en': 'English',
  'es': 'Español',
  'nl': 'Nederlands',
'ru': 'Русский',
  'pt': 'Português'
};

/**
 * Selected language, default English.
 * @type {string}
 */
Ardublockly.LANG = 'en';

/**
 * We keep a local copy of the default language in case translations cannot
 * be found in the injected language file.
 * @type {Object}
 */
Ardublockly.DEFAULT_LANG_TEXT = {};


/** Initialize the page language. */
Ardublockly.initLanguage = function() {
  // Save the current default language ID to check if it has been changed
  var defaultLang = Ardublockly.LANG;

  // Check server settings and url language, url gets priority
  Ardublockly.LANG = Ardublockly.getUrlLanguage() ||
      Ardublockly.getLanguageSetting() || Ardublockly.LANG;

  Ardublockly.populateLanguageMenu(Ardublockly.LANG);

  if (defaultLang !== Ardublockly.LANG) {
      Ardublockly.duplicateDefaultLang();
      Ardublockly.injectLanguageJsSources(Ardublockly.LANG);
      Ardublockly.updateLanguageText();
  }
};

/**
 * Get the language previously set by the user from the server settings.
 * @return {string} Language saved in the server settings.
 */
Ardublockly.getLanguageSetting = function() {
  //TODO: Server feature still to be implemented, for now return default
  return null;
};

/**
 * Get the language selected from the URL, format '?lang=en'.
 * @return {string} Selected language.
 */
Ardublockly.getUrlLanguage = function() {
  var langKey = 'lang';
  var val = location.search.match(new RegExp('[?&]' + langKey + '=([^&]+)'));
  var language = val ? decodeURIComponent(val[1].replace(/\+/g, '%20')) : '';
  if (Ardublockly.LANGUAGE_NAME[language] === undefined) {
    language = null;
  }
  return language;
};

/**
 * Populates the settings language selection menu.
 * @param {!string} selectedLang Language to be marked as selected.
 */
Ardublockly.populateLanguageMenu = function(selectedLang) {
  var languageMenu = document.getElementById('language');
  languageMenu.options.length = 0;

  for (var lang in Ardublockly.LANGUAGE_NAME) {
    var option = new Option(Ardublockly.LANGUAGE_NAME[lang], lang);
    if (lang == selectedLang) {
      option.selected = true;
    }
    languageMenu.options.add(option);
  }
  languageMenu.onchange = Ardublockly.changeLanguage;
};

/**
 * Because new languages are injected by overwriting Ardublockly.LOCALISED_TEXT
 * we keep a local copy of the default language (included in the html header) so
 * that we can still retrieve these strings if the translation cannot be found.
 */
Ardublockly.duplicateDefaultLang = function() {
  for (var textId in Ardublockly.LOCALISED_TEXT) {
    Ardublockly.DEFAULT_LANG_TEXT[textId] = Ardublockly.LOCALISED_TEXT[textId];
  }
};

/** Updates the page text strings with the new language. */
Ardublockly.updateLanguageText = function() {
  for (var textId in Ardublockly.LOCALISED_TEXT) {
    var textStrings = document.getElementsByClassName('translatable_' + textId);
    for (var i = 0; i < textStrings.length; i++) {
      textStrings[i].innerHTML = Ardublockly.getLocalStr(textId);
    }
  }
};

/**
 * Injects the language JavaScript files into the html head element.
 * @param {string} langKey Dictionary key for the language to inject, must also
 *     be JS file name.
 */
Ardublockly.injectLanguageJsSources = function(langKey) {
  var head = document.getElementsByTagName('head')[0];

  // Retrieve and inject Ardublockly translations synchronously
  var appLangJsLoad = document.createElement('script');
  var request = ArdublocklyServer.createAjaxRequest();
  var appLangJdPath = 'msg/' + langKey + '.js';
  try {
    request.open('GET', appLangJdPath, false);
    request.send('');
    appLangJsLoad.text = request.responseText;
  } catch (e) {
    // Display an alert to indicate we cannot load languages
    Ardublockly.alertMessage(
        Ardublockly.getLocalStr('noServerTitle'),
        Ardublockly.getLocalStr('noServerNoLangBody'),
        false);
    // But still asynchronous lazy load so at least some text gets translated
    appLangJsLoad.src = appLangJdPath;
  }
  head.appendChild(appLangJsLoad);

  // Retrieve and inject Blockly translations asynchronously
  var blocklyLangJsLoad = document.createElement('script');
  blocklyLangJsLoad.src = '../blockly/msg/js/' + langKey + '.js';
  head.appendChild(blocklyLangJsLoad);
};

/** Saves the blocks and reloads with a different language. */
Ardublockly.changeLanguage = function() {
  // Store the blocks for the duration of the reload only
  Ardublockly.saveSessionStorageBlocks();

  var languageMenu = document.getElementById('language');
  var newLang = encodeURIComponent(
      languageMenu.options[languageMenu.selectedIndex].value);
  var search = window.location.search;
  if (search.length <= 1) {
    search = '?lang=' + newLang;
  } else if (search.match(/[?&]lang=[^&]*/)) {
    search = search.replace(/([?&]lang=)[^&]*/, '$1' + newLang);
  } else {
    search = search.replace(/\?/, '?lang=' + newLang + '&');
  }

  window.location = window.location.protocol + '//' +
      window.location.host + window.location.pathname + search;
};

/**
 * Finds and returns the requests string in the localised language.
 * If the translation is not returned, it fetches the original language string.
 * @param {string} stringId
 * @return {!string} The localised, original, or an empty string.
 */
Ardublockly.getLocalStr = function(stringId) {
  var text = Ardublockly.LOCALISED_TEXT[stringId];
  if (!text) {
    console.log('Localised text string ID "' + stringId + '" does not exists!');
  }
  return text || Ardublockly.DEFAULT_LANG_TEXT[stringId] || '';
};

**Comment by carlosperate** [comment]
Is the russian text in the blocks rendering correctly? I am having issues with the rendering of your ru.js file even on a normal text editor, maybe there is problems with the file encoding? I assume this is not how it is normally displayed on your environment:

![encoding_ru](https://cloud.githubusercontent.com/assets/4189262/21852841/8ed960d8-d80c-11e6-9d08-927fdfb2e3eb.png)

**Comment by mrobotby** [comment]
BIG Thanks @carlosperate . All is working correctly when I changed ANSI to UTF-8.

**Comment by carlosperate** [comment]
Glad you got it working. If you'd like to submit a Pull Request it would be great to have Russian as an available language!
