### ISSUE TITLE
Function type INT is it available in Ardublockly?

### ISSUE THREAD

**Issue by mrobotby** [carlosperate/ardublockly#138]
Function type INT is it available in Ardublockly?

**Comment by carlosperate** [comment]
Hi,

Functions with return types are currently supported, is this what you meant?

![untitled](https://cloud.githubusercontent.com/assets/4189262/22247131/182eb31a-e230-11e6-82d6-4ceeb2fe91e9.png)

**Comment by carlosperate** [comment]
I assume the question has been answered, feel free to reopen this issue otherwise.
