### ISSUE TITLE
Main menu does not show translated strings

### ISSUE THREAD

**Issue by microspace** [carlosperate/ardublockly#140]
![image](https://cloud.githubusercontent.com/assets/2958584/21983794/ac12bab2-dc14-11e6-96e0-80d33af1b1a6.png)
I've got russian translation file ru.js in ardublockly\ardublockly\msg directory. 
I've taken ru.js from this issue, with right encoding.
https://github.com/carlosperate/ardublockly/issues/136
Main menu entries are still in English. What am I doing wrong?

**Comment by carlosperate** [comment]
There are two areas to translate, the blockly strings (which you have already done) and the strings from the Ardublockly front end, which you'll find in https://github.com/carlosperate/ardublockly/tree/master/ardublockly/msg
