### ISSUE TITLE
Building Ardublockly for Linux and Mac under Windows

### ISSUE THREAD

**Issue by MarceloFariaz** [carlosperate/ardublockly#145]
### Is it possible to build and pack Ardublockly for linux/mac under Windows?
My intention is to get files like those from the [releases](https://github.com/carlosperate/ardublockly/releases) page.

**Comment by carlosperate** [comment]
Unfortunately that is not possible, the build can only target the platform where it's running.

**Comment by MarceloFariaz** [comment]
I imagined.. =/
Thanks, @carlosperate!
