### ISSUE TITLE
Translation of the Top Menu

### ISSUE THREAD

**Issue by mrobotby** [carlosperate/ardublockly#150]
Hi. Where I can find files to translate and edit Top Menu? File - Edit - Program - Examples - Help

<img width="294" alt="2017-02-13 12 39 01" src="https://cloud.githubusercontent.com/assets/14249390/22878122/8e98aec0-f1e9-11e6-8861-45b996b7f811.png">

**Comment by pteacher** [comment]
I guess it can be only done editing index.html file in ardublockly folder.

**Comment by mrobotby** [comment]
Thanks. I will check your advice, because I need Russian version too)

**Comment by mrobotby** [comment]
I translated to Russian this menu. Thank you @pteacher Do you know how to connect Arduino 101 in Arduino IDE to this Ardublockly program?
