### ISSUE TITLE
Where to edit Big Round Icons -Upload, Compile, Open in Arduino IDE?

### ISSUE THREAD

**Issue by mrobotby** [carlosperate/ardublockly#152]
I can't find file where to edit/delete this buttons. Does anyone know?
<img width="217" alt="2017-02-15 10 07 36" src="https://cloud.githubusercontent.com/assets/14249390/22963921/d88f580c-f366-11e6-939b-b76339d41bf0.png">

**Comment by pteacher** [comment]
Im not sure, about reason you want to do that, but you can delete them in ardublockly\index.html file
lines 123-125
`          <a id="button_ide_left" class="waves-effect waves-light waves-circle btn-floating z-depth-1-half arduino_yellow"><i id="button_ide_left_icon" class="mdi-action-open-in-browser"></i></a>
          <a id="button_ide_middle" class="waves-effect waves-light waves-circle btn-floating z-depth-1-half arduino_teal"><i id="button_ide_middle_icon" class="mdi-navigation-check"></i></a>
          <a id="button_ide_large" class="waves-effect waves-light waves-circle btn-floating z-depth-1-half arduino_orange"><i id="button_ide_large_icon" class="mdi-av-play-arrow"></i></a>`

**Comment by mrobotby** [comment]
谢谢 @pteacher ！

**Comment by carlosperate** [comment]
Looks like @pteacher has been able to answer your question (thanks!), so I'll close this issue. Let me know if you still need any clarifications.
