### ISSUE TITLE
4 pins stepper motor

### ISSUE THREAD

**Issue by alcir** [carlosperate/ardublockly#156]
Since many Arduino kits came with a 28BYJ-48 Stepper Motor with ULN2003 driver, that uses 4 pins, what about a stepper block where you can choose between 2 or 4 pins?

**Comment by carlosperate** [comment]
Hi Alessio,

Am I correct in that we talked about a stepper block via hangout a while ago? If you are the same person, then yes please! if you can send a PR and I can have a look and upgrade the block to select the 2 or 4 pin configuration.

**Comment by alcir** [comment]
Yes. I will push the code asap.
Thank you.

**Comment by carlosperate** [comment]
Feature has been merged by #157.
