### ISSUE TITLE
Compiler location window appear behind the IDE

### ISSUE THREAD

**Issue by MarceloFariaz** [carlosperate/ardublockly#175]
If the IDE is maximized the user does not can see the compiler location window. 
**Other related problem:** doing multiple clicks opens multiple windows.
**OS:** Windows 10
![capture](https://user-images.githubusercontent.com/12167941/26982057-79d556b2-4d0d-11e7-8d2d-4fe2084d0c28.PNG)

**Comment by carlosperate** [comment]
Thanks for the report Marcelo, this has been fixed by changing the implementation to use the Electron file browsers instead. More info in https://github.com/carlosperate/ardublockly/issues/37.
This is in the master branch, but hasn't been released officially yet.
