### ISSUE TITLE
Hover Tips/Tooltips

### ISSUE THREAD

**Issue by TechplexEngineer** [carlosperate/ardublockly#20]
It would be great to have tooltips which appear when one hovers over buttons. This helps new users learn the interface. Most of the time adding a title="" attribute will suffice.

Great work!

**Comment by carlosperate** [comment]
Yes indeed, that is a great suggestion. I'll add it once I start touching the front end gui again.

**Comment by carlosperate** [comment]
It took me a while to actually implement it, but it's now done. Thanks again for the suggestion!
