### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by elahroodi** [carlosperate/ardublockly#211]
Hi there
Can I ask you please help me how to add Arduino_stm32 board at below link to the "compilersettings.py" file like this one:
   'ESP8266 Huzzah': 'esp8266:esp8266:generic',
 
I'm using stm32f103c8t6

https://github.com/rogerclarkmelbourne/Arduino_STM32

Many thanks.

**Comment by JMRUIZ1** [comment]
Hello,  thanks for email, but at moment I can not answer you because I am
ill,,maybe next week I will be fit again....

next week I will get in contact again...


Thanks

2018-06-13 16:05 GMT+02:00 Ehsan Moradi <notifications@github.com>:

**Comment by elahroodi** [comment]
Solved Thanks
This is the answer 
'STM32': 'Arduino_STM32:STM32F1:genericSTM32F103C'
