### ISSUE TITLE
Continuation of the Ardublockly project

### ISSUE THREAD

**Issue by pmagyar** [carlosperate/ardublockly#250]
Hello,

I noticed that the project is currently no longer being edited (see last commit).
I created a new organization called "ardublockly" and forked the project.
If you are interested in the project, please have a look here:
https://github.com/ardublockly/ardublockly

I would be happy if helping hands would contact me to bring the project back to life.
Please contact me here: https://github.com/ardublockly/ardublockly/discussions/1

**Comment by pmagyar** [comment]
Hello,

I noticed that the project is currently no longer being edited (see last commit).
I created a new organization called "adublockly" and forked the project.
If you are interested in the project, please have a look here:
https://github.com/ardublockly/ardublockly

I would be happy if helping hands would contact me to bring the project back to life.
Please contact me here: https://github.com/ardublockly/ardublockly/discussions/1

**Comment by coloz** [comment]
great!

**Comment by coloz** [comment]
i develop a new software：
https://github.com/coloz/b4a
