### ISSUE TITLE
Comment popup window jumps over tool menu

### ISSUE THREAD

**Issue by MadTooler** [carlosperate/ardublockly#35]
The text of the comments window pops up, sort of, over the top of the tool/block menu bar after clicking back on "?" to hide and re-display comments. 

Initial entry:
![image](https://cloud.githubusercontent.com/assets/16729670/12532596/92ada066-c1dd-11e5-93a5-b8aec615610c.png)

1st Click on "?" to close: (BTW, seems related that comments do not show in arduino source code until  the block is moved around)
![image](https://cloud.githubusercontent.com/assets/16729670/12532608/c83893c6-c1dd-11e5-8fc2-57061aeb9c20.png)

2nd click back on "?" to view comment: 
![image](https://cloud.githubusercontent.com/assets/16729670/12532616/f9a7f050-c1dd-11e5-859b-47aab80285f2.png)

Additional view and hide clicks respond the same as 2nd until the block is moved with the comment popup exposed then it works along with the comment now present in the arduino source code:
![image](https://cloud.githubusercontent.com/assets/16729670/12532626/2c8db540-c1de-11e5-8b9d-c7f39f130f44.png)

Once the comment is closed, it will again act the same way with the text top left of window until you drag the block, then, it does pop back in place.  However, when the comment is hidden, there is a brief blip of the text in the correct popup location before it fully closes.  Additionally, removal or changes of the comment do not update in arduino source code until the block is drug around.

**Comment by carlosperate** [comment]
Thanks for the detailed report! This was an odd one, and seemed to be a bug with chromium. So, I updated it to the latest version and I haven't been able to replicate again, so hopefully that should have fixed it.

**Comment by MadTooler** [comment]
It is no longer bouncing around on the screen, or leaving any artifacts, but it still does not update the arduino source code until I drag around the block.

**Comment by carlosperate** [comment]
Thanks for confirming. 

The code generation is a different issue with how often the code is generated, I'll open a different issue for that one.
