### ISSUE TITLE
HTTP1.1 error

### ISSUE THREAD

**Issue by leekj1840** [carlosperate/ardublockly#41]
![default](https://cloud.githubusercontent.com/assets/16893391/12634050/ad36c004-c5b9-11e5-8f5b-be8f3dd120eb.PNG)

python ver 3.5....

why this error..??

closure/goog/base.js existence

**Comment by leekj1840** [comment]
https://developers.google.com/blockly/hacking/closure

download success thanks

**Comment by carlosperate** [comment]
It looked in your original screenshot like you had the closure library set up correctly, did you have to do anything else to get it running?
