### ISSUE TITLE
labels editing is skewed

### ISSUE THREAD

**Issue by MadTooler** [carlosperate/ardublockly#42]
Win 7 64b pro...

The editing of labels and some variables has the text in an awkward location:
![image](https://cloud.githubusercontent.com/assets/16729670/12694174/b441239a-c6e9-11e5-93e6-595eb2af2fe0.png)
![image](https://cloud.githubusercontent.com/assets/16729670/12694175/cf96ac32-c6e9-11e5-99cc-725b470f93bf.png)

**Comment by carlosperate** [comment]
Wow, I haven't seen that in a long time. Is that running the desktop application? or is it running in any other browser? Are there any specific steps required to reproduce it?

**Comment by MadTooler** [comment]
That was running from the desktop fresh from starting the program.

This is with the latest build.

**Comment by carlosperate** [comment]
Yes, I can definitely reproduce it, I'll have to look what change introduced this issue.

**Comment by carlosperate** [comment]
Should be back to normal now.
