### ISSUE TITLE
Zoom icons function

### ISSUE THREAD

**Issue by MadTooler** [carlosperate/ardublockly#46]
Is the cross hairs zoom button suppose to work as a zoom to extents/all, or as it currently functions where it zooms to the center of mass at the 100% setting?

If I start with a large or spread out program like this zoomed out to see it all:
![image](https://cloud.githubusercontent.com/assets/16729670/12736604/48e463a2-c917-11e5-9be6-b684e5049824.png)

then clicked on cross hair:
![image](https://cloud.githubusercontent.com/assets/16729670/12736614/5c9017a2-c917-11e5-982e-941c2de0baef.png)

**Comment by carlosperate** [comment]
It is mean to reset the zoom level to the default value set on Blockly injection, which in this case would the 100% ([/ardublockly/ardublockly_blockly.js#L48](https://github.com/carlosperate/ardublockly/blob/master/ardublockly/ardublockly_blockly.js#L48))

**Comment by MadTooler** [comment]
Thanks.
