### ISSUE TITLE
Uploading the sketch to the Arduino in UBUNTU 14.04 LTS

### ISSUE THREAD

**Issue by RubensQRZ** [carlosperate/ardublockly#51]
Dear Carlos, 

When I try to upload the sketch to the Arduino using UBUNTU 14.04 LTS, I get this error:

![db4k - ubuntu](https://cloud.githubusercontent.com/assets/12803665/13469046/695f34fc-e084-11e5-818c-0e0a840b7bdd.jpg)

Best regards

Rubens

**Comment by carlosperate** [comment]
Could you copy the contents of the `ArdublocklySketch.ino` here? It would also be useful if you could upload the `ardublockly.log` (and `ardublockly2.log` if it exists) files somewhere where I could download them.
Which version of the Arduino IDE are you using?

**Comment by RubensQRZ** [comment]
Hi Carlos, 

I did not find the ardublockly.log file

The Arduino IDE version is – 1:1.0.5+dfsg2-2

I copied the CLI command: 

/usr/bin/arduino --upload --port /dev/ttyACM0 --board arduino:avr:uno /home/labvad/DB4k/DB4KA915/ArdublocklySketch/ArdublocklySketch.ino

to the Terminal, and I got the same problem: I receive a window with the message: bad file selected: Processing can only open its own sketches and other files ending in .ino or .pde.

And then the arduino IDE opens with the code.

Thank you

Best regards

Rubens.
[ArdublocklySketch.ino.tar.gz](https://github.com/carlosperate/ardublockly/files/165130/ArdublocklySketch.ino.tar.gz)
[Pythonshell_ArdublocklyServer_Ubuntu.pdf](https://github.com/carlosperate/ardublockly/files/165131/Pythonshell_ArdublocklyServer_Ubuntu.pdf)

**Comment by carlosperate** [comment]
I see, you are using Arduino 1.0.5, which does not support the command line interface. You will need 1.6 or higher (I would recommend the latest one available from the Arduino website).

**Comment by RubensQRZ** [comment]
thank you so much,

**Comment by carlosperate** [comment]
No problem, glad you got it working.
