### ISSUE TITLE
Error including Servo.h

### ISSUE THREAD

**Issue by carloslfu** [carlosperate/ardublockly#82]
Hi, when I add a new servo related block the `#include <Servo.h>` is incomplete:

![ardublockly3](https://cloud.githubusercontent.com/assets/5993168/15439236/96362900-1e95-11e6-96b0-5b91351ec756.jpg)

**Comment by carlosperate** [comment]
Hi Carlos, thanks for reporting this. The fix has been delivered in https://github.com/carlosperate/ardublockly/commit/0b4e3e460a58cf2149e1e03e89de350dbfa769cd, so it should be working with the latest master. I'll make sure to update the online demo as well.

**Comment by carloslfu** [comment]
Thanks @carlosperate .
