### ISSUE TITLE
Configure Ardublockly to locate Arduino IDE

### ISSUE THREAD

**Issue by RimishRobolab** [carlosperate/ardublockly#87]
How to configure Ardublockly to locate Arduino IDE for prepackaged executable file and core version. It's very urgent

**Comment by carlosperate** [comment]
Hi @RimishRobolab,

Do you need any specific clarification about the configuration, or just a general need for step-by-step instructions? I could answer any questions you might have right now, but the instructions with screenshots might take a couple of days since I won't have much spare time until the weekend.

**Comment by RimishRobolab** [comment]
Hello Sir,
I need detail step by step instructions with screenshots.
because of time constraints, as of now you can provide me step by step instruction without screenshots and after this weekend whenever you have time you can add screenshots also.

**Comment by RimishRobolab** [comment]
Hello Sir, 
I did not get any answer from you. Can you please give me solution as soon as possible.
I have many queries to ask you in the pipeline.

**Comment by aethaniel** [comment]
@RimishRobolab, filling the settings with the path where Arduino IDE is located is pretty straightforward.
What do you miss?

**Comment by RimishRobolab** [comment]
Yes, I already got it but did not post here. When I click on path, the browse window came behind ardublockly. So I noticed it later becuase most of the time browse windows come infront of UI

**Comment by carlosperate** [comment]
Yeah, sorry about that, haven't generated the "quick start" guide yet. However that specific issue is already documented in the FAQs: https://github.com/carlosperate/ardublockly/wiki/FAQs

**Comment by synetics** [comment]
Error while running start.py 
webbrowser.Error: could not locate runnable browser
This was solved by editing webbrowser.get() to webnrowser.open()
Now I am able to run start.py without error.
Thanks
