### ISSUE TITLE
Generating Blocks For Arduino

### ISSUE THREAD

**Issue by RimishRobolab** [carlosperate/ardublockly#94]
After Placing the block I want to generate the code for block
How to add code for
1) header files
2) Macro Definitions
3) Global Variables outside setup function and loop function
4) how to add code to setup function
5) how to add code to loop function
6) how to place user defined function definition

basically, I want to that how all this above code added to their specific places
e.g for adding variable you have used Blockly.Arduino.addVariable()
so I want to know all above syntax and definitions.
![image](https://cloud.githubusercontent.com/assets/19488511/16264107/381e4856-3895-11e6-9324-f0bd0fef32d8.png)

**Comment by carlosperate** [comment]
I'll start updating the https://github.com/carlosperate/ardublockly/wiki/Create-Blocks wiki page with more information (right now it's just a "first draft"). If there is something you need with urgency let me know and I'll try to document it there.
