### ISSUE TITLE
Change sketch name when a saved sketch is opened

### ISSUE THREAD

**Issue by RubensQRZ** [carlosperate/ardublockly#97]
Dear Carlos

I made a little change in the "loadUserXmlFile" function in order to change the sketch name at the interface to the name of the file being loaded.

After the "Ardublockly.renderContent()" function call, I included this code:

      var filename_with_extencion = files[0].name;
      var string_size = filename_with_extencion.length;
      var filename = filename_with_extencion.substr(0,(string_size-4));	
      document.getElementById('sketch_name').value = filename;

Best regards

Rubens.

**Comment by carlosperate** [comment]
Thanks Rubens! Implemented in https://github.com/carlosperate/ardublockly/commit/2be5b8b10018de162cc4bacd60da8dd77163c8c5.
